library(ggplot2)
library(plyr)
library(dplyr)
library(reshape2)
library(parallel)
options(mc.cores = 24)
library(stringr)
library(RColorBrewer)
library(GenomicRanges)
library(tidyr)
library(forcats)
library(tibble)
library(readr)
library(webreadr)
library(ggforce)
#ibrary(ggraph)
library(ggthemes,lib.loc = "~/R/x86_64-redhat-linux-gnu-library/3.2/")
library(plotly)
